repos:
  - repo: https://github.com/softwaremill/scala-pre-commit-hooks
    rev: v0.5.1
    hooks:
      - id: sbt-unused-imports #includes fatal warnings, arguments optional
        args: [ --scope=test:compile ]
      - id: sbt-scalafmt