version = 3.11.5
runner.dialect = scala3

maxColumn = 80

binPack {
  parentConstructors = Oneline
  importSelectors = fold
}

newlines {
  avoidForSimpleOverflow = all
  ignoreInSyntax = false
  inInterpolation = avoid
  source = fold
}

rewrite {
  rules = [
    RedundantBraces,
    RedundantParens,
    SortModifiers,
    RemoveSemicolons,
  ]
  imports {
    selectors = fold
    sort = ascii
  }
  sortModifiers.preset = styleGuide
}

align.preset = most